demo1/booktest/urls.py
from . import views
from django.conf.urls import url
app_name='booktest'
urlpatterns=[
        url(r'^$',views.index,name="index"),
        url(r'^list/$',views.list,name="list"),
        url(r'^detail/(\d+)/$',views.detail,name="detail"),

        url(r'^deletehero/(\d+)/$',views.deletehero,name="deletehero"),
        url(r'^deletebook/(\d+)/$',views.deletebook,name="deletebook"),

        url(r'^addhero/(\d+)/$', views.addhero, name="addhero"),

        url(r'^addBook/$',views.addBook,name="addBook"),

    ]

demo1/demo1/urls.py
from django.contrib import admin
from django.urls import path
from django.conf.urls import url, include


urlpatterns = [
    path('admin/', admin.site.urls),
    url('',include('booktest.urls',namespace="booktest"))
    # 空任意匹配

]

demo1/booktest/models.py
from django.db import models

# Create your models here.

class BookInfo(models.Model):
    tile=models.CharField(max_length=20)
    pub_date=models.DateTimeField(auto_now=True)
    def __str__(self):
        return self.tile

class HeroInfo(models.Model):
    name=models.CharField(max_length=20)
    # gender=models.CharField(default=True)
    gender=models.CharField(max_length=5,choices=(("man","男"),("women","女")))
    type=models.CharField(max_length=5,choices=(("man","男"),("women","女")),default="man")
    content=models.CharField(max_length=100)
    book=models.ForeignKey(BookInfo,on_delete=models.CASCADE)
    def __str__(self):
        return self.name
    def __str__(self):
        return self.content

demo1/booktest/views.py
from django.shortcuts import render
from django.http import HttpResponse
from django.template import loader
from .models import BookInfo,HeroInfo
from django.shortcuts import *



# Create your views here.
def index(request):

    # 获取模块
    # return  HttpResponse("这里是首页 <a href='/list/'>跳转</a>")
    # temp1=loader.get_template('booktest/index.html')
    # book1=BookInfo.objects.all()
    # result=temp1.render({})
    # 使用模块渲染字典参数
    # result=temp1.render({})
    # 将渲染的结果返回
    return render(request,"booktest/index.html",{"username":"zzy"})


# def list(request):
#     return  HttpResponse("这里是列表页 <a href='/booktest/detail/'>跳转</a>")
# def detail(request):
#     return  HttpResponse("这里是详情页 <a href='/booktest/index/'>跳转</a>")
def list(request):
    # temp2=loader.get_template('booktest/list.html')
    books=BookInfo.objects.all()
    # result=temp2.render({"book":books})
    # return  HttpResponse(result)
    return  render(request,"booktest/list.html",{"book":books})



    # return  HttpResponse("这里是列表%s"%(s,))
def detail(request,id):
    # temp3=loader.get_template("booktest/detail.html")
    # book=BookInfo.objects.get(pk = id)
    # result=temp3.render({"book":book})
    # return  HttpResponse(result)

    book=BookInfo.objects.get(pk=id)
    return render(request,"booktest/detail.html",{"book":book})

    # return  HttpResponse("这里是%s详情页<a href='/'>跳转到首页</a>"%(id,))
def deletebook(request,id):
    Book=BookInfo.objects.get(pk = id)
    Book.delete()
    return redirect(reverse("booktest:list",))



def deletehero(request,id):
    hero =HeroInfo.objects.get(pk =id)
    bookid=hero.book.id
    hero.delete()
    #
    return  redirect(reverse("booktest:detail",args=(bookid,)))

    # return HttpResponse("SHNSDF")
    # return  HttpResponseRedirect("/detail/"+ str(bookid)+ "/")
#
def addhero(request,id):
    book = BookInfo.objects.get(pk = id)
    if request.method == "GET":
        return render(request,"booktest/addhero.html",{"book":book})
    elif request.method == "POST":
        name = request.POST.get("username")
        content = request.POST.get("content")
        gender = request.POST.get("gender")
        gender1 = request.POST.get("gender1")
        hero = HeroInfo()
        hero.name = name
        hero.content = content
        hero.book = book
        hero.gender=gender
        hero.type=gender1
        hero.save()
        return redirect(reverse("booktest:detail",args=(id,)))


def addBook(request):
        if request.method == "GET":
            return render(request, "booktest/addBook.html")
        elif request.method == "POST":
            tile = request.POST.get("title")
            hero = BookInfo()
            hero.tile = tile
            hero.save()
            return redirect(reverse("booktest:list"))

demo1/templates/booktest/addBook.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<form action="{% url 'booktest:addBook' %}" method="post">
    名字<input type="text" name="title">
    <br>
        <input type="submit" value="添加">
</form>

</body>
</html>

demo1/templates/booktest/addhero.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>

 <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<body>
<h3>当前书名:{{book.tile}}</h3>
<form method="post" class="form-horizontal" role="form">
    <div class="form-group">
        <label for="firstname" class="col-sm-2 control-label">人物名称</label>
        <div class="col-sm-3">
            <input name="username" type="text" class="form-control" id="firstname" placeholder="请输入人物">
        </div>
    </div>

    <div class="form-group">
        <label for="lastname" class="col-sm-2 control-label">技能</label>
        <div class="col-sm-3">
            <input name="content" type="text" class="form-control" id="lastname"placeholder="请输入技能">
        </div>
    </div>


      <div class="form-group">
            <label for="gender" class="col-sm-2 control-label">英雄性别</label>
            <div class="col-sm-6">
                <select name="gender" id="gender" class="form-control">
                    <option value="man">男</option>
                    <option value="women">女</option>
                </select>
            </div>
        </div>


    <div class="form-group">
            <label for="gender" class="col-sm-2 control-label">英雄性别</label>
            <div class="col-sm-6">
               男： <input type="radio" checked name="gender1" value="man">
                女： <input type="radio" name="gender1" value="women">
            </div>
        </div>


    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <button type="submit" class="btn btn-default">添加</button>
        </div>
    </div>

</form>

<!--<form action="{% url 'booktest:addhero' book.id %}" method="post">-->
    <!--名字<input type="text" name="username">-->
    <!--<br>-->
    <!--英雄<input type="text"name="content">-->
    <!--<br>-->
    <!--<input type="submit" value="添加">-->
<!--</form>-->

</body>
</html>

demo1/templates/booktest/detail.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
<body>

<div id="content" class="container">
    <h1>详情页</h1>
    <h3>当前书籍为:{{book.tile}}</h3>
        {% if book.heroinfo_set.count %}
        <h3>当前角色:</h3>
        <br>
            <ul>
                {% for hero in book.heroinfo_set.all %}
                <li>姓名:&nbsp&nbsp&nbsp{{hero.name}}----{{hero.content}}---{{hero.gender}}
                    <a href="{% url 'booktest:deletehero' hero.id %}">删除</a></li>
                {% endfor%}
            </ul>
        <br>
            {% else%}
                 <h3>没有角色</h3>
        {% endif%}

<a class="btn btn-success" href="{% url 'booktest:addhero' book.id %}">添加英雄</a>

<a href="/">返回首页</a>
    </div>
<br>
</body>
</html>

demo1/templates/booktest/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link rel="stylesheet" href="/static/css/main.css">
    <!--<script src="/static/js/main.js"></script>-->
</head>
<!-- jQuery (Bootstrap 的所有 JavaScript 插件都依赖 jQuery，所以必须放在前边) -->
<script src="https://cdn.jsdelivr.net/npm/jquery@1.12.4/dist/jquery.min.js"></script>
<!-- 加载 Bootstrap 的所有 JavaScript 插件。你也可以根据需要只加载单个插件。 -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/js/bootstrap.min.js"></script>
<link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">



<body>

        <h2>首页books</h2>
        <!--{% for book in books %}-->
        <!--<a href="/detail/{{book.id}}">DFADF{{book.tile}}<br><hr></a>-->
        <!--{% endfor %}-->
        <span>当前用户:</span><span class="username">{{username}}</span>
        <!--{# <a href="/list/" style="color: sandybrown">进入列表页</a> #}-->

    <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
        <ol class="carousel-indicators">
            <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
            <li data-target="#carousel-example-generic" data-slide-to="1"></li>
            <li data-target="#carousel-example-generic" data-slide-to="2"></li>
            <li data-target="#carousel-example-generic" data-slide-to="3"></li>
        </ol>
        <div id="container" style="padding-left: 250px;padding-top: 10px">
        <!-- Wrapper for slides -->
        <div class="carousel-inner" role="listbox">
            <div class="item active">
                <img src="/static/img/3.jpg" alt="..." >
                <div class="carousel-caption">
                    ...
                </div>
            </div>
            <div class="item">
                <img src="/static/img/1.jpg" alt="...">
                <div class="carousel-caption">
                    ...
                </div>
            </div>

            <div class="item">
                <img src="/static/img/2.jpg" alt="...">
                <div class="carousel-caption">
                    ...
                </div>
            </div>
             <div class="item">
                <img src="/static/img/banner4.png" alt="...">
                <div class="carousel-caption">
                    ...
                </div>
            </div>
            ...
        </div>

        <!-- Controls -->
        <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
            <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
            <span class="sr-only">Previous</span>
        </a>
        <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
            <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
            <span class="sr-only">Next</span>
        </a>
    </div>
    </div>
        <br>
        <a href="{% url 'booktest:list' %}">进入列表页</a>
</body>
</html>

demo1/templates/booktest/list.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@3.3.7/dist/css/bootstrap.min.css" rel="stylesheet">
</head>
<body>
<h2 style="text-align: center;margin-bottom: 30px">列表</h2>
 {% for book in book %}
<div id="container"style="text-align: center;font-size:30px">
    {# <a href="/detail/{{book.id}}">{{book.tile}}--{{book.pub_date}}<br><hr></a> #}

    <a href="{% url 'booktest:detail' book.id %}">{{book.tile}}--{{book.pub_date}}</a>
    <a class="btn btn-default"style="color: lightgreen;" href="{% url 'booktest:deletebook' book.id %}">删除</a>

</div>
    {% endfor %}
<a class="btn btn-default"style="color: lightgreen;" href="{% url 'booktest:addBook'%}">添加数据</a>
</body>
</html>